config/routes.rb
Rails.application.routes.draw do
  
  get 'copies/create'

  get 'copies/destroy'

  resources :games do
    resources :reviews, except: [:show, :index]
  end   

  resources :copies, only: [:create, :destroy]

  resources :genres
  
  devise_for :users
  
  get 'static_pages/home'

   root 'static_pages#home'

end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ActiveRecord::Base
    has_many :game

    validates_presence_of :name
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :active)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<div class="col-md-2"></div>
  <div class="col-md-8">
      
      <%= form_for @genre, :html => { :class => "form-horizontal genre" } do |f| %>
      
          <% if @genre.errors.any? %>
          <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title"><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h3>
            </div>
            <div class="panel-body">
              <ul>
              <% @genre.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      
        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
          <%= error_span(@genre[:name]) %>
        </div>
        <div class="control-group">
          <label>
            <%= f.check_box :active %>
            <%= f.label :active %>
          </label>
          <%= error_span(@genre[:active]) %>
        </div>
      
      
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  genres_path, :class => 'btn btn-default' %>
      
      <% end %>
    </div>
  <div class="col-md-2">

app/views/genres/edit.html.erb
<%- model_class = Genre -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/genres/index.html.erb
<%- model_class = Genre -%>
<div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:active) %></th>
          <!--<th><%#= model_class.human_attribute_name(:created_at) %></th>-->
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= link_to genre.id, genre_path(genre) %></td>
            <td><%= genre.name %></td>
            <td><%= genre.active %></td>
            <!--<td><%#=l genre.created_at %></td>-->
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_genre_path(genre), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          genre_path(genre),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_genre_path,
                :class => 'btn btn-primary' %>
  </div>
<div class="col-md-1"></div>

app/views/genres/new.html.erb
<%- model_class = Genre -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/genres/show.html.erb
<%- model_class = Genre -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @genre.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @genre.active %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              genres_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_genre_path(@genre), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              genre_path(@genre),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>