config/routes.rb
Rails.application.routes.draw do
  
  get 'copies/create'

  get 'copies/destroy'

  resources :games do
    resources :reviews, except: [:show, :index]
  end   

  resources :copies, only: [:create, :destroy]

  resources :genres
  
  devise_for :users
  
  get 'static_pages/home'

   root 'static_pages#home'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_game, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /reviews/new
  def new
    #@review = Review.new
    @review = Game.find(params[:game_id]).reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    #@review = Review.new(review_params)
    @review = Game.find(params[:game_id]).reviews.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @game, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @game, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location:  @game }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @game, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :game_id, :rating, :content)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="container">
  <%= form_for ([@game,@review]), :html => { :class => "form-horizontal review" } do |f| %>

      <% if @review.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="control-group">
      <%= f.label :rating, :class => 'control-label' %>
      <div class="controls">
       <div id="star-rating"></div>
      </div>
      <%= error_span(@review[:rating]) %>
    </div>
    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => 'form-control', rows: 6 %>
      </div>
      <%= error_span(@review[:content]) %>
    </div>

    <br><br>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              game_path(@game), :class => 'btn btn-default' %>

  <% end %>
</div>
<script>
  $('#star-rating').raty({
    path: '/assets',
    number: 10,
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:game_id) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.id, review_path(review) %></td>
        <td><%= review.user_id %></td>
        <td><%= review.game_id %></td>
        <td><%= review.rating %></td>
        <td><%= review.content %></td>
        <td><%=l review.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_review_path(review), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      review_path(review),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_review_path,
            :class => 'btn btn-primary' %>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%#= @review.game.title %>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @review.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game_id) %>:</strong></dt>
  <dd><%= @review.game_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @review.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @review.content %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reviews_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_path(@review), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_path(@review),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>